version: "3"

services:
  psqldb:
    image: "postgres:latest"

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER     = dev 
      - POSTGRES_PASSWORD = hooper2@ 
      - POSTGRES_DB       = default_database

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: "dpage/pgadmin4"

    environment:
      PGADMIN_DEFAULT_EMAIL   : "dev@superadmin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"

    ports:
      - "16543:80"

    depends_on:
      - psqldb

    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge