version: '3'

services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "default_pswd"
      MYSQL_DATABASE: "default_db"
    ports:
      - "3306:3306"
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 16544:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge